#----------------------------------------------------------------------------
#       Make Workspace
#
# $Id$
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/bob/MPC-MPC_4_1_0/mwc.pl -type make -include mpc -features boost=1 -value_template add_references=1 -static cck.mwc
#
#----------------------------------------------------------------------------


all: implementation-target ccktc-target TCommandProcessor TConstraints TConversions TCsvParser TDependencyPrinter TErrorPrinter TFileSystem TFilesBinaryEqual TGenerator TGeneratorStatistic TKeywordParameterParser TLineCollector TParameterParser TSourceFile TSpecialRegexCharacterPrefixer TSystem TTableIndex TTemplateLoader TTemplateProcessor TTokenizer TVerticalTableBuilder

depend: implementation-target-depend ccktc-target-depend TCommandProcessor-depend TConstraints-depend TConversions-depend TCsvParser-depend TDependencyPrinter-depend TErrorPrinter-depend TFileSystem-depend TFilesBinaryEqual-depend TGenerator-depend TGeneratorStatistic-depend TKeywordParameterParser-depend TLineCollector-depend TParameterParser-depend TSourceFile-depend TSpecialRegexCharacterPrefixer-depend TSystem-depend TTableIndex-depend TTemplateLoader-depend TTemplateProcessor-depend TTokenizer-depend TVerticalTableBuilder-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@cd implementation && $(MAKE) -f Makefile.implementation $(@)
	@cd ccktc && $(MAKE) -f Makefile.ccktc $(@)
	@cd implementation/test/TCommandProcessor && $(MAKE) -f Makefile.TCommandProcessor $(@)
	@cd implementation/test/TConstraints && $(MAKE) -f Makefile.TConstraints $(@)
	@cd implementation/test/TConversions && $(MAKE) -f Makefile.TConversions $(@)
	@cd implementation/test/TCsvParser && $(MAKE) -f Makefile.TCsvParser $(@)
	@cd implementation/test/TDependencyPrinter && $(MAKE) -f Makefile.TDependencyPrinter $(@)
	@cd implementation/test/TErrorPrinter && $(MAKE) -f Makefile.TErrorPrinter $(@)
	@cd implementation/test/TFileSystem && $(MAKE) -f Makefile.TFileSystem $(@)
	@cd implementation/test/TFilesBinaryEqual && $(MAKE) -f Makefile.TFilesBinaryEqual $(@)
	@cd implementation/test/TGenerator && $(MAKE) -f Makefile.TGenerator $(@)
	@cd implementation/test/TGeneratorStatistic && $(MAKE) -f Makefile.TGeneratorStatistic $(@)
	@cd implementation/test/TKeywordParameterParser && $(MAKE) -f Makefile.TKeywordParameterParser $(@)
	@cd implementation/test/TLineCollector && $(MAKE) -f Makefile.TLineCollector $(@)
	@cd implementation/test/TParameterParser && $(MAKE) -f Makefile.TParameterParser $(@)
	@cd implementation/test/TSourceFile && $(MAKE) -f Makefile.TSourceFile $(@)
	@cd implementation/test/TSpecialRegexCharacterPrefixer && $(MAKE) -f Makefile.TSpecialRegexCharacterPrefixer $(@)
	@cd implementation/test/TSystem && $(MAKE) -f Makefile.TSystem $(@)
	@cd implementation/test/TTableIndex && $(MAKE) -f Makefile.TTableIndex $(@)
	@cd implementation/test/TTemplateLoader && $(MAKE) -f Makefile.TTemplateLoader $(@)
	@cd implementation/test/TTemplateProcessor && $(MAKE) -f Makefile.TTemplateProcessor $(@)
	@cd implementation/test/TTokenizer && $(MAKE) -f Makefile.TTokenizer $(@)
	@cd implementation/test/TVerticalTableBuilder && $(MAKE) -f Makefile.TVerticalTableBuilder $(@)

.PHONY: implementation-target
implementation-target:
	@cd implementation && $(MAKE) -f Makefile.implementation all

.PHONY: implementation-target-depend
implementation-target-depend:
	@cd implementation && $(MAKE) -f Makefile.implementation depend

.PHONY: ccktc-target
ccktc-target: implementation-target
	@cd ccktc && $(MAKE) -f Makefile.ccktc all

.PHONY: ccktc-target-depend
ccktc-target-depend:
	@cd ccktc && $(MAKE) -f Makefile.ccktc depend

.PHONY: TCommandProcessor
TCommandProcessor: implementation-target
	@cd implementation/test/TCommandProcessor && $(MAKE) -f Makefile.TCommandProcessor all

.PHONY: TCommandProcessor-depend
TCommandProcessor-depend:
	@cd implementation/test/TCommandProcessor && $(MAKE) -f Makefile.TCommandProcessor depend

.PHONY: TConstraints
TConstraints: implementation-target
	@cd implementation/test/TConstraints && $(MAKE) -f Makefile.TConstraints all

.PHONY: TConstraints-depend
TConstraints-depend:
	@cd implementation/test/TConstraints && $(MAKE) -f Makefile.TConstraints depend

.PHONY: TConversions
TConversions: implementation-target
	@cd implementation/test/TConversions && $(MAKE) -f Makefile.TConversions all

.PHONY: TConversions-depend
TConversions-depend:
	@cd implementation/test/TConversions && $(MAKE) -f Makefile.TConversions depend

.PHONY: TCsvParser
TCsvParser: implementation-target
	@cd implementation/test/TCsvParser && $(MAKE) -f Makefile.TCsvParser all

.PHONY: TCsvParser-depend
TCsvParser-depend:
	@cd implementation/test/TCsvParser && $(MAKE) -f Makefile.TCsvParser depend

.PHONY: TDependencyPrinter
TDependencyPrinter: implementation-target
	@cd implementation/test/TDependencyPrinter && $(MAKE) -f Makefile.TDependencyPrinter all

.PHONY: TDependencyPrinter-depend
TDependencyPrinter-depend:
	@cd implementation/test/TDependencyPrinter && $(MAKE) -f Makefile.TDependencyPrinter depend

.PHONY: TErrorPrinter
TErrorPrinter: implementation-target
	@cd implementation/test/TErrorPrinter && $(MAKE) -f Makefile.TErrorPrinter all

.PHONY: TErrorPrinter-depend
TErrorPrinter-depend:
	@cd implementation/test/TErrorPrinter && $(MAKE) -f Makefile.TErrorPrinter depend

.PHONY: TFileSystem
TFileSystem: implementation-target
	@cd implementation/test/TFileSystem && $(MAKE) -f Makefile.TFileSystem all

.PHONY: TFileSystem-depend
TFileSystem-depend:
	@cd implementation/test/TFileSystem && $(MAKE) -f Makefile.TFileSystem depend

.PHONY: TFilesBinaryEqual
TFilesBinaryEqual: implementation-target
	@cd implementation/test/TFilesBinaryEqual && $(MAKE) -f Makefile.TFilesBinaryEqual all

.PHONY: TFilesBinaryEqual-depend
TFilesBinaryEqual-depend:
	@cd implementation/test/TFilesBinaryEqual && $(MAKE) -f Makefile.TFilesBinaryEqual depend

.PHONY: TGenerator
TGenerator: implementation-target
	@cd implementation/test/TGenerator && $(MAKE) -f Makefile.TGenerator all

.PHONY: TGenerator-depend
TGenerator-depend:
	@cd implementation/test/TGenerator && $(MAKE) -f Makefile.TGenerator depend

.PHONY: TGeneratorStatistic
TGeneratorStatistic: implementation-target
	@cd implementation/test/TGeneratorStatistic && $(MAKE) -f Makefile.TGeneratorStatistic all

.PHONY: TGeneratorStatistic-depend
TGeneratorStatistic-depend:
	@cd implementation/test/TGeneratorStatistic && $(MAKE) -f Makefile.TGeneratorStatistic depend

.PHONY: TKeywordParameterParser
TKeywordParameterParser: implementation-target
	@cd implementation/test/TKeywordParameterParser && $(MAKE) -f Makefile.TKeywordParameterParser all

.PHONY: TKeywordParameterParser-depend
TKeywordParameterParser-depend:
	@cd implementation/test/TKeywordParameterParser && $(MAKE) -f Makefile.TKeywordParameterParser depend

.PHONY: TLineCollector
TLineCollector: implementation-target
	@cd implementation/test/TLineCollector && $(MAKE) -f Makefile.TLineCollector all

.PHONY: TLineCollector-depend
TLineCollector-depend:
	@cd implementation/test/TLineCollector && $(MAKE) -f Makefile.TLineCollector depend

.PHONY: TParameterParser
TParameterParser: implementation-target
	@cd implementation/test/TParameterParser && $(MAKE) -f Makefile.TParameterParser all

.PHONY: TParameterParser-depend
TParameterParser-depend:
	@cd implementation/test/TParameterParser && $(MAKE) -f Makefile.TParameterParser depend

.PHONY: TSourceFile
TSourceFile: implementation-target
	@cd implementation/test/TSourceFile && $(MAKE) -f Makefile.TSourceFile all

.PHONY: TSourceFile-depend
TSourceFile-depend:
	@cd implementation/test/TSourceFile && $(MAKE) -f Makefile.TSourceFile depend

.PHONY: TSpecialRegexCharacterPrefixer
TSpecialRegexCharacterPrefixer: implementation-target
	@cd implementation/test/TSpecialRegexCharacterPrefixer && $(MAKE) -f Makefile.TSpecialRegexCharacterPrefixer all

.PHONY: TSpecialRegexCharacterPrefixer-depend
TSpecialRegexCharacterPrefixer-depend:
	@cd implementation/test/TSpecialRegexCharacterPrefixer && $(MAKE) -f Makefile.TSpecialRegexCharacterPrefixer depend

.PHONY: TSystem
TSystem: implementation-target
	@cd implementation/test/TSystem && $(MAKE) -f Makefile.TSystem all

.PHONY: TSystem-depend
TSystem-depend:
	@cd implementation/test/TSystem && $(MAKE) -f Makefile.TSystem depend

.PHONY: TTableIndex
TTableIndex: implementation-target
	@cd implementation/test/TTableIndex && $(MAKE) -f Makefile.TTableIndex all

.PHONY: TTableIndex-depend
TTableIndex-depend:
	@cd implementation/test/TTableIndex && $(MAKE) -f Makefile.TTableIndex depend

.PHONY: TTemplateLoader
TTemplateLoader: implementation-target
	@cd implementation/test/TTemplateLoader && $(MAKE) -f Makefile.TTemplateLoader all

.PHONY: TTemplateLoader-depend
TTemplateLoader-depend:
	@cd implementation/test/TTemplateLoader && $(MAKE) -f Makefile.TTemplateLoader depend

.PHONY: TTemplateProcessor
TTemplateProcessor: implementation-target
	@cd implementation/test/TTemplateProcessor && $(MAKE) -f Makefile.TTemplateProcessor all

.PHONY: TTemplateProcessor-depend
TTemplateProcessor-depend:
	@cd implementation/test/TTemplateProcessor && $(MAKE) -f Makefile.TTemplateProcessor depend

.PHONY: TTokenizer
TTokenizer: implementation-target
	@cd implementation/test/TTokenizer && $(MAKE) -f Makefile.TTokenizer all

.PHONY: TTokenizer-depend
TTokenizer-depend:
	@cd implementation/test/TTokenizer && $(MAKE) -f Makefile.TTokenizer depend

.PHONY: TVerticalTableBuilder
TVerticalTableBuilder: implementation-target
	@cd implementation/test/TVerticalTableBuilder && $(MAKE) -f Makefile.TVerticalTableBuilder all

.PHONY: TVerticalTableBuilder-depend
TVerticalTableBuilder-depend:
	@cd implementation/test/TVerticalTableBuilder && $(MAKE) -f Makefile.TVerticalTableBuilder depend

project_name_list:
	@echo ccktc-target
	@echo implementation-target
	@echo TCommandProcessor
	@echo TConstraints
	@echo TConversions
	@echo TCsvParser
	@echo TDependencyPrinter
	@echo TErrorPrinter
	@echo TFileSystem
	@echo TFilesBinaryEqual
	@echo TGenerator
	@echo TGeneratorStatistic
	@echo TKeywordParameterParser
	@echo TLineCollector
	@echo TParameterParser
	@echo TSourceFile
	@echo TSpecialRegexCharacterPrefixer
	@echo TSystem
	@echo TTableIndex
	@echo TTemplateLoader
	@echo TTemplateProcessor
	@echo TTokenizer
	@echo TVerticalTableBuilder
