;PSPad user HighLighter definition file
[Settings]
Name=CCK TC-Commands
HTMLGroup=0
Label=0
FileType=*.tccmd
CommentString=
ANSIComment=0
PasComment=0
SlashComment=0
CComment=0
SpecComment=0
BasComment=0
FoxComment=0
REMComment=0
ExclComment=0
ByComment=0
SharpComment=1
PerCentComment=0
SinglQComment=0
DblQComment=0
SQLComment=0
SingleQuote=0
DoubleQuote=1
Preprocessors=0
IndentChar=
UnIndentChar=
TabWidth=4
CaseSensitive=1
KeyWordChars=-
CodeExplorer=ftUnknown
[KeyWords]
--[ENTRY]["Option Name"]=
-[ENTRY]["Short"]=
[ReservedWords]
[KeyWords2]
[KeyWords3]
