;PSPad user HighLighter definition file
[Settings]
Name=CCK Template
HTMLGroup=0
Label=0
FileType=*.tpl.h
CommentString=[COMMENT]
ANSIComment=0
PasComment=0
SlashComment=0
CComment=0
SpecComment=0
BasComment=0
FoxComment=0
REMComment=0
ExclComment=0
ByComment=0
SharpComment=0
PerCentComment=0
SinglQComment=0
DblQComment=0
SQLComment=0
SingleQuote=0
DoubleQuote=0
Preprocessors=0
IndentChar=
UnIndentChar=
TabWidth=4
CaseSensitive=1
KeyWordChars=._
CodeExplorer=ftUnknown
[KeyWords]
!ENTRY!["Tag Name"]!READ_TOP_DOWN!=
[ReservedWords]
!ENTRY!["Tag Name"]!READ_TOP_DOWN!...=
[KeyWords2]
!ENTRY!["Tag Name"]!READ_TOP_DOWN!.=
[KeyWords3]
!ENTRY!["Tag Name"]!READ_TOP_DOWN!..=
