#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -D_REENTRANT -I"$(BOOST_ROOT)/include/$(BOOST_VERSION)" -I"$(BOOST_ROOT)/." -I"../implementation"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"." -L"$(BOOST_ROOT)/lib" -L"../implementation"
CCC           = $(CXX)
MAKEFILE      = Makefile.ccktc
DEPENDENCIES  = .depend.$(MAKEFILE)
BTARGETDIR    = ../output/bin/
BIN           = $(BTARGETDIR)ccktc$(EXESUFFIX)$(EXEEXT)
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O
LDLIBS        = -l"implementation$(LIBSUFFIX)" -l"$(BOOST_STATIC_LIB_PREFIX)boost_system$(BOOST_CFG)" -l"$(BOOST_STATIC_LIB_PREFIX)boost_regex$(BOOST_CFG)" -l"$(BOOST_STATIC_LIB_PREFIX)boost_filesystem$(BOOST_CFG)" -l"$(BOOST_STATIC_LIB_PREFIX)boost_program_options$(BOOST_CFG)" -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = ccktc$(OBJEXT)
SRC           = ccktc.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = $(STATICFLAGS)
DEPLIBS       = $(foreach lib, implementation$(LIBSUFFIX) "$(BOOST_STATIC_LIB_PREFIX)boost_system$(BOOST_CFG)" "$(BOOST_STATIC_LIB_PREFIX)boost_regex$(BOOST_CFG)" "$(BOOST_STATIC_LIB_PREFIX)boost_filesystem$(BOOST_CFG)" $(BOOST_STATIC_LIB_PREFIX)boost_program_options$(BOOST_CFG), $(foreach libpath, . $(BOOST_ROOT)/lib ../implementation, $(wildcard $(libpath)/lib$(lib).a)))

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(BIN)

$(BIN): $(OBJS) $(DEPLIBS)
	@$(TESTDIRSTART) "$(BTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(BTARGETDIR)"
	$(LINK.cc) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

generated: $(GENERATED_DIRTY)
	@-:

ccktc$(OBJEXT): ccktc.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ccktc.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(BIN)

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) -Wall -Wextra -pedantic -fsyntax-only $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------


depend:
	-$(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

-include $(DEPENDENCIES)
