Description="code-creation-kit template style"

Default        = { Colour="#000000" }
Canvas         = { Colour="#ffffff" }
Number         = { Colour="#000000" }
Escape         = { Colour="#a31515" }
String         = { Colour="#a31515" }
StringPreProc  = { Colour="#0000ff" }
BlockComment   = { Colour="#008000" }
PreProcessor   = { Colour="#0000ff" }
LineNum        = { Colour="#2b91af" }
Operator       = { Colour="#000000" }
LineComment = BlockComment
Interpolation  = Escape

Keywords = {
  { Colour= "#000000", Bold=true },
  { Colour= "#0000A0", Bold=true },
  { Colour= "#A00000", Bold=true },
  { Colour= "#AAAA00", Bold=true },
  { Colour= "#888800", Bold=true },
}
